config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "homes#top"
  get "home/about"=>"homes#about"
  get "search" => "searches#search"

  devise_for :users
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  get "books/favorited/desc" => "books#index_favorited_desc" ,as: "books_favorited_desc"
  get "index/star/desc" => "books#index_star_desc", as: "books_star_desc"
  resources :tags do
    get "books" , to: "searches#tag_search"
  end

  resources :users, only: [:index,:show,:edit,:update]do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments,dependent: :destroy
  has_many :book_tags,dependent: :destroy
  has_many :tags,through: :book_tags

  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}
  validates :star, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1}, presence: true

  def favorited_by?(user)
    favorites.exists?(user_id:user.id)
  end


  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end


  def save_tag(sent_tags)
  # タグが存在していれば、タグの名前を配列として全て取得
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    # 現在取得したタグから送られてきたタグを除いてoldtagとする
    old_tags = current_tags - sent_tags
    # 送信されてきたタグから現在存在するタグを除いたタグをnewとする
    new_tags = sent_tags - current_tags

    # 古いタグを消す
    old_tags.each do |old|
      self.tags.delete　Tag.find_by(name: old)
    end

    # 新しいタグを保存
    new_tags.each do |new|
      new_book_tag = Tag.find_or_create_by(name: new)
      self.tags << new_book_tag
    end
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def show
    @book = Book.find(params[:id])
    @user = User.find(@book.user_id)
    @book_tags = @book.tags
    @book_comment=BookComment.new
  end

  def index
    @tag_list=Tag.all
    @book=Book.new
    @books = Book.all.order(created_at: :desc)
  end

  def index_favorited_desc
    @tag_list=Tag.all
    @book=Book.new
    @books= Book.includes(:favorites).sort {|a,b| b.favorites.size <=> a.favorites.size}
  end

  def index_star_desc
    @tag_list=Tag.all
    @book=Book.new
    @books = Book.all.order(star: :desc)
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    tag_list=params[:book][:name].split(nil)
    if @book.save
      @book.save_tag(tag_list)
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
    unless @book.user==current_user
      render book_path(@book.id)
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title,:body,:star)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div clss="form-group" id="rating-form">
    <label>評価：</label>
    <%= f.hidden_field :star %>
  </div>
  <div class="form-group">
    <%= f.label"tag (スペースで区切ると複数タグ登録できます)" %>
    <%= f.text_field :name,class:"form-control"%>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>




<script>
  $('#rating-form').raty({
    starOn: "<%= asset_path('star-on.png') %>",
    starOff: "<%= asset_path('star-off.png') %>",
    scoreName: 'book[star]'
  });
</script>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user_id) do %>
          <%= image_tag book.user.get_profile_image, size:'50x50' %>
          <% end %>
        </td>
        <td><%= link_to book.title,book %></td>
        <td><%= book.body %></td>
        <td id="star-rate-<%= book.id %>">評価：</td>

<script>
  $('#star-rate-<%= book.id %>').raty({
    size: 36,
    starOff:  '<%= asset_path('star-off.png') %>',
    starOn : '<%= asset_path('star-on.png') %>',
    readOnly: true,
    score: <%= book.star %>,
  });
</script>

        <td>
          <% book.tags.each do |tag| %>
          <%= link_to tag_books_path(tag_id: tag.id) do %>
          <%= tag.name %>:<%= tag.books.count %>
          <% end %>
          <% end %>
        </td>

        <td id="favorite_buttons_<%= book.id %>">
        <%= render "favorites/favorites" ,book:book %>
        </td>

        <td>
          <%= book.book_comments.count %>コメント
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_tag_list.html.erb
      <% if tag_list != nil %>
        <% tag_list.each do |tag|%>
        <%= link_to tag_books_path(tag_id: tag.id) do %>
          <span><%=tag.name %></span>:
          <span><%="(#{tag.books.count})" %></span>
        <% end %>
        <% end %>
      <% end %>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		<%= render "layouts/errors" ,obj:@book %>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', @book %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <%= render 'layouts/errors', obj: @book %>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <span><%= link_to "新着順", books_path %></span> | <span><%= link_to "いいね順", books_favorited_desc_path %></span> | <span><%= link_to "評価順", books_star_desc_path %></span>
      <div>
        <%= render "tag_list",tag_list: @tag_list %>
      </div>
      <div id="book_index"><%= render 'index', books: @books%></div>
    </div>
  </div>
</div>

app/views/books/index_favorited_desc.html.erb
<div class='container px-5 px-sm-0'>
  <%= render 'layouts/errors', obj: @book %>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <span><%= link_to "新着順", books_path %></span> | <span><%= link_to "いいね順", books_favorited_desc_path %></span>
      <div>
        <%= render 'tag_list',tag_list: @tag_list %>
      </div>
      <div id="book_index"><%= render 'index', books: @books%></div>
    </div>
  </div>
</div>

app/views/books/index_star_desc.html.erb
<div class='container px-5 px-sm-0'>
  <%= render 'layouts/errors', obj: @book %>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <span><%= link_to "新着順", books_path %></span> | <span><%= link_to "いいね順", books_favorited_desc_path %></span> | <span><%= link_to "評価順", books_star_desc_path %></span>
      <div>
        <%= render 'tag_list',tag_list: @tag_list %>
      </div>
      <div id="book_index"><%= render 'index', books: @books%></div>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info',user:@user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: Book.new %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
          <td><%= link_to(@book.user) do %>
            <%= image_tag @book.user.get_profile_image, size:"100x100" %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, @book %></td>
          <td><%= @book.body %></td>

          <td>
            <% @book_tags.each do |tag| %>
            <%= link_to tag_books_path(tag_id: tag.id) do %>
              <%= tag.name %>:<%= tag.books.count %>
            <% end %>
            <% end %>
          </td>

          <td id="favorite_buttons_<%= @book.id %>">
          <%= render "favorites/favorites" ,book:@book %>
          </td>

          <td>
            <p>コメント数：<%= @book.book_comments.count %></p>
          </td>

          <% if @book.user==current_user %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success" %></td>
            <td><%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger"%></td>
          <% end %>
        </tr>
      </table>

      <table class='table'>
      <tbody id="book_comments_<%= @book.id %>">
        <%= render "book_comments/book_comments",book:@book %>
      </tbody>
      </table>


      <div>
        <%= render "book_comments/book_comment",book:@book,book_comment:@book_comment %>
      </div>

    </div>
  </div>
</div>