config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "homes#top"
  get "home/about"=>"homes#about"
  get "search" => "searches#search"

  devise_for :users
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  get "books/favorited/desc" => "books#index_favorited_desc" ,as: "books_favorited_desc"
  get "index/star/desc" => "books#index_star_desc", as: "books_star_desc"
  resources :tags do
    get "books" , to: "searches#tag_search"
  end

  resources :users, only: [:index,:show,:edit,:update]do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController


  before_action :authenticate_user!

  def search
    @range = params[:range]
    @order = params[:order]

    if @order == "New"

      if @range == "User"
        @users = User.looks(params[:search], params[:word])
        @word=params[:word]
      elsif @range == "Book"
        @books = Book.looks(params[:search], params[:word])
        @word=params[:word]
      elsif @range == "Tag"
        @tags = Tag.looks(params[:search], params[:word])
        @word=params[:word]
      end

    elsif @order == "Old"

      if @range == "User"
        users = User.looks(params[:search], params[:word])
        @users = user.order(id: "DESC")
        @word=params[:word]
      elsif @range == "Book"
        books = Book.looks(params[:search], params[:word])
        @books = books.order(id: "DESC")
        @word=params[:word]
      elsif @range == "Tag"
        tags = Tag.looks(params[:search], params[:word])
        @tags = tags.order(id: "DESC")
        @word=params[:word]
      end

    elsif @order == "Popular"

      if @range == "User"
        users = User.looks(params[:search], params[:word])
        @users=users.includes(:followers).sort {|a,b| b.followers.size <=> a.followers.size}
        @word=params[:word]
      elsif @range == "Book"
        books = Book.looks(params[:search], params[:word])
        @books=books.includes(:favorites).sort {|a,b| b.favorites.size <=> a.favorites.size}
        @word=params[:word]
      elsif @range == "Tag"
        tags = Tag.looks(params[:search], params[:word])
        @tags = tags.includes(:books).sort {|a,b| b.books.size <=> a.books.size}
        @word=params[:word]
      end

    end
  end


  def tag_search
    @tag = Tag.find(params[:tag_id])
    @books = @tag.books.all
  end


  def search_favorited_desc

  end


end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/search.html.erb
<table class="table table-hover table-inverse">

  <% if @range == "User" %>
    <h2>User search for "<%= @word %>"</h2>
    <thead>
      <tr>
        <th>    </th>
      <th>user image</th>
      <th>name</th>
      <th>introduction</th>
    </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td>    </td>
          <td><%= image_tag user.get_profile_image,size:'50x50' %></td>
          <td>
            <%= link_to user_path(user.id) do %>
            <%= user.name %>
            <% end %>
          </td>
          <td><%= user.introduction %></td>
        </tr>
      <% end %>
    </tbody>
  <% elsif @range == "Book" %>
    <h2>Book title search for "<%= @word %>"</h2>
    <thead>
      <tr>
        <th>    </th>
        <th>title</th>
        <th>opinion</th>
        <th>favorites</th>
        <th>tags</th>
        <th>user</th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
        <tr>
          <td>    </td>
          <td>
            <%= link_to book_path(book.id) do %>
            <%= book.title %>
            <% end %>
          </td>
          <td><%= book.body %></td>
          <td>♥<%= book.favorites.count %></td>

          <td>
            <% book.tags.each do |tag| %>
              <%= link_to tag_books_path(tag_id: tag.id) do %>
                <%= tag.name %>:<%= tag.books.count %>
              <% end %>
            <% end %>
          </td>

          <td>
            <%= link_to user_path(book.user_id) do %>
            <%= image_tag book.user.get_profile_image,size:'50x50' %><br>
            <%= book.user.name %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  <% elsif @range == "Tag" %>
    <h2>Tag search for "<%= @word %>"</h2>
    <thead>
      <tr>
        <td>    </td>
        <td>name</td>
        <td>count</td>
      </tr>
    </thead>
    <tbody>
      <% @tags.each do |tag| %>
        <tr>
          <td>    </td>
          <td>
            <%= link_to tag_books_path(tag_id: tag.id) do %>
            <%= tag.name %>
            <% end %>
          </td>
          <td><%= tag.books.count %></td>
        </tr>
      <% end %>
    </tbody>
  <% end %>
</table>

app/views/searches/tag_search.html.erb
<table class="table table-hover table-inverse">
<h2>  search for "<%= @tag.name %>"Tag</h2>

    <thead>
      <tr>
        <th>    </th>
        <th>title</th>
        <th>opinion</th>
        <th>favorites</th>
        <th>tags</th>
        <th>user</th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
        <tr>
          <td>    </td>
          <td>
            <%= link_to book_path(book.id) do %>
            <%= book.title %>
            <% end %>
          </td>
          <td><%= book.body %></td>
          <td>♥<%= book.favorites.count %></td>
          <td>
            <% book.tags.each do |tag| %>
              <%= link_to tag_books_path(tag_id: tag.id) do %>
                <%= tag.name %>:<%= tag.books.count %>
              <% end %>
            <% end %>
          </td>
          <td>
            <%= link_to user_path(book.user_id) do %>
            <%= image_tag book.user.get_profile_image,size:'50x50' %><br>
            <%= book.user.name %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>